
<?php
require 'module/Users/view/users/utils/user_label.php';
?>
<br>
<div><?php echo $user_labels['changePassword']?></div>
<form action="users/setting/processPassword">
	<div class="error mycenter" id="passwordError" hidden="hidden"
		style="width: 200px;"><?php echo $user_labels[changePasswordError]?></div>
	<br>
	<table class="mycenter">
		<tr>
			<th class="showInfoTd"><?php echo $user_labels['oldPassword']?></th>
			<td><input type="password" name="old_password"></td>
		</tr>
		<tr>
			<th class="showInfoTd"><?php echo $user_labels['newPassword']; ?></th>
			<td><input type="password" name="password"></td>
		</tr>
		<tr>
			<th class="showInfoTd"><?php echo $user_labels['confirmNewPassword']?></th>
			<td><input type="password" name="confirm_password"></td>
		</tr>
		<tr>
		    <th></th>
			<td><input type="submit" id="submit_change_password_button" value="<?php echo $user_labels['submit']?>"></td>
		</tr>
	</table>
</form>
<div style="width: 20px;" class="mycenter">
	<img hidden="hidden" id="loadingImg" alt="" src="/images/loading.gif">
</div>
<div class="mycenter" hidden="hidden" id="changeSuccess"
	style="width: 610px">
	<br> <br>
	<h3><?php echo $user_labels[confirm_closeWindow] ?></h3>
	<br> <br>
</div>
<!-- The Password setting validation plugin -->
<script src="/js/change-password.js" type="text/javascript"></script>
