<?php 
include_once 'module/Users/view/layout/top_panel.php';
$this->headTitle()->prepend('Setting');
?>
<h2>My Uploads</h2>

<?php echo $this->photo_filename; ?>

<div class="wrap">
      
        <script src="/js/confirm.js" type="text/javascript"></script>
        
       
        
        
        
        <div id="tabs">
        	<ul>
        		<li><a href="#tabs-1">个人资料</a></li>
        		<li><a href="#tabs-2">Second</a></li>
        		<li><a href="#tabs-3">Third</a></li>
        	</ul>
        	<div id="tabs-1">
        	   <div>
        	       <!-- The container for the uploaded files-->
                    <div id="files" class="files" style="height: 149px;">
                        <?php 
                        
                        $filename = realpath('./module/Users/data/thumbnail/'.$this->photo_filename);
                        echo $filename;
                        if (file_exists($filename)) {
                        	echo '<div>
                            <br>          	       
                	           <img  alt="抱歉网络忙" src="';
                        	echo  $filename;
                            echo '" style="height: 130px;" title="修改头像">
                	        <br>
            	        </div>';
                        } else {
                            echo '<div>
                            <br>          	       
                	           <img  alt="抱歉网络忙" src="/images/defaultphoto.jpg" style="height: 130px;" title="修改头像">
                	        <br>
            	        </div>';
                        }?>
                        
                    </div>
                    
        	        <br>
                    <!-- The fileinput-button span is used to style the file input field as button -->
        	        <span class="btn btn-success fileinput-button">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>更新头像</span>
                        <!-- The file input field used as target for the file upload widget -->
                        <input id="fileupload" type="file" name="files[]" multiple>
                    </span>
                    
                           
                    <br>
                    <br>
                    
                    
                     
        	       
        	   </div>
        	</div>
        	<div id="tabs-2">Phasellus mattis tincidunt nibh. Cras orci urna, blandit id, pretium vel, aliquet ornare, felis. Maecenas scelerisque sem non nisl. Fusce sed lorem in enim dictum bibendum.</div>
        	<div id="tabs-3">Nam dui erat, auctor a, dignissim quis, sollicitudin eu, felis. Pellentesque nisi urna, interdum eget, sagittis et, consequat vestibulum, lacus. Mauris porttitor ullamcorper augue.</div>
        </div>
    </div> <!-- /.wrap -->
    
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>

<!-- The basic File Upload plugin -->
<script src="/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/js/jquery.fileupload-image.js"></script>

<!-- The file Upload image  -->  
<script src="/js/upload-image.js"></script>
