
<?php
require 'module/Users/view/users/utils/user_label.php';
?>
<br>
<div class="content-title">去帮忙</div>
    <form action="" method="post" class="mycenter">
        <div class="mycenter single-element">
        <input type="email" name="email" placeholder="电子邮件地址" >
        </div>
        <div class="searchButton mycenter">
        <input type="submit" id="search_submit" value="搜索" >
        </div>
    </form>
    <table class="mycenter">
      <tr>
        <td><img alt="photo" src="images/defaultphoto.jpg" class="target_photo"></td>
        <td>Tom</td>
        <td>eat 2 pies in 10 mins</td>
        <td>+</td>
      </tr>
    </table>

