
<?php
require 'module/Users/view/users/utils/user_label.php';
?>
<div class="content-title">
    <div class="ui-corner-all">我的帮手群</div>
</div>
<div class="helpers_group">
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
    <div class="personalInfo ui-corner-all">
        <img alt="" src="images/defaultphoto.jpg" class="personalPhoto ui-corner-all">
        <p>Tom</p>
        <p>Happy Daddy</p>
        <p style="float: right">x</p>
    </div>
</div>
<div id="helpers_page_div"></div>

<!-- helper.js -->
<script src="/js/helper.js"></script>
<script src="/js/bootstrap-paginator.min.js"></script>