
<?php
require 'module/Users/view/users/utils/user_label.php';
?>
<br>
<div class="content-title">找帮手</div>
<div class="content-single">
    <form action="" method="post" class="mycenter">
        <div class="mycenter single-element">
        <input type="email" name="email" placeholder="电子邮件地址" >
        </div>
        <div class="searchButton mycenter">
        <input type="submit" id="search_submit" value="搜索" >
        </div>
    </form>
    <table class="mycenter">
      <tr>
        <td><img alt="photo" src="images/defaultphoto.jpg" class="target_photo"></td>
        <td>Tom</td>
        <td>eat 2 pies in 10 mins</td>
        <td>+</td>
      </tr>
    </table>
    <div>
        <h5 class="mycenter">注册帮手中没有这个电子邮件地址，<br>我们将通过邮件对该地址发出您的邀请.</h5>
        <form action="" class="mycenter">
            <div class="inviteButton mycenter">
            <input type="submit" id="invite_helper_submit" value="发出邀请">
            </div>
            <div class="mycenter single-element">
            <textarea rows="5" cols="40" placeholder="补充信息有利于对方更清楚的了解您的请求" style="width: 270px"></textarea>
            </div>
        </form>
    </div>
</div>

