
<?php
require 'module/Users/view/users/utils/user_label.php';
?>
<br>
<div class="content-title">等待回复的帮手</div>
<div id="accordion_waiting">
	<h5>新的帮手</h5>
	<div class="accordion_div">
		<table class="mycenter">
			<tr>
				<td><img alt="photo" src="images/defaultphoto.jpg"
					class="target_photo"></td>
				<td>Tom</td>
				<td>eat 2 pies in 10 mins</td>
				<td>I want to be your helper</td>
				<td>+</td>
			</tr>
			<tr>
				<td><img alt="photo" src="images/defaultphoto.jpg"
					class="target_photo"></td>
				<td>Tom</td>
				<td>eat 2 pies in 10 mins</td>
				<td>I want to be your helper</td>
				<td>+</td>
			</tr>
		</table>
	</div>
	<h5>等待验证</h5>
	<div>
		<table class="mycenter">
			<tr>
				<td><img alt="photo" src="images/defaultphoto.jpg"
					class="target_photo"></td>
				<td>Tony</td>
				<td>eat 2 pies in 10 mins</td>
				<td>waiting</td>
				<td>+</td>
			</tr>
			<tr>
				<td><img alt="photo" src="images/defaultphoto.jpg"
					class="target_photo"></td>
				<td>Jessica</td>
				<td>eat 2 pies in 10 mins</td>
				<td>rejected</td>
				<td>+</td>
			</tr>
		</table>
	</div>
</div>

