<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<?php require_once 'index_label.php';?>
<div class="wrap">
	<div class="slider">

		<section id="slider">

			<div class="flexslider">

				<ul class="slides clearfix">

					<li><img src="images/slider/slide-1.jpg" alt="" />
						<hgroup class="caption-1">
						    <h2><?php echo $labels[title1];?></h2>
							<h1 class="tcolor"><?php echo $labels[title2];?></h1>
						</hgroup></li>

				</ul>
				<!--/ .slides-->

			</div>
			<!--/ .flexslider-->

		</section>
		<!--/ #slider-->
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
