<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<div class="wrap">
	<div class="slider">

		<section id="slider">

			<div class="flexslider">

				<ul class="slides clearfix">

					<li><img src="images/slider/slide-1.jpg" alt="" />
						<hgroup class="caption-1">
							<h2>正确的事通常也是</h2>
							<h1 class="tcolor">简单的！</h1>
						</hgroup></li>

				</ul>
				<!--/ .slides-->

			</div>
			<!--/ .flexslider-->

		</section>
		<!--/ #slider-->
	</div>
	<!--/ .slider-->
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
