<?php
$this->headTitle()->prepend('Pending Requests');
require 'module/Users/view/users/utils/user_label.php';
?>

<div class="wrap">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1"><?php echo "等待回应的申请"?></a></li>

		</ul>
		<div id="tabs-1" style="height: 800px">
		  <div class="tab-left">
		      <?php echo $this->partial('users/org-manager/SPRtab-left.phtml');?>
		  </div>
		  <div class="tab-right">
		      <?php echo $this->partial('users/org-manager/SPRtab-right.phtml');?>
		  </div>
		  
		</div>
	</div>
</div>
<script src="/js/showPendingR.js" type="text/javascript"></script>

