<?php
require 'module/Users/view/users/utils/user_label.php';
?>
			<div id="showPhoto">
			<div id="files" class="files" style="height: 149px;">
	           <br><img alt=<?php echo $user_labels[pleaseUpdate]?>
		          class="ui-state-default ui-corner-all" title="logo"
		          src="<?php echo $this->url('users/media', array('action' => 'showImage', 'key' => $org->id, 'subaction' => 'logoThumb'));?>"
		          style="height: 130px; width: 120px;">
            </div>
                <p><?php echo $org->org_name;?></p>
            </div>
            <dl class="shortcut-menue">
                <dt><?php echo $user_labels[shortCutChannel]?></dt>
                <dd>
                    <ul>
                        <li  class="ui-state-default ui-corner-all iconSize" title=".ui-icon-locked">
                            <a target="_blank" href="/users/setting/changePassword"><span class="ui-icon ui-icon-locked"></span></a>
                        </li>
                        <li class="iconText">
                            <a target="_blank" href="/users/setting/changePassword"><?php echo $user_labels[changePassword]?></a>
                        </li>
                    </ul>
                </dd>
            </dl>
          
          


