<!-- - - - - - - - - - - - - Slider - - - - - - - - - - - - - - - -->
<div class="wrap">
    <h2>test controller index</h2>
    
    <button id="genMock">generate mock users</button>
    <form action="/users/register/process" method="post">
        <input type="text" name="first_name">
        <input type="text" name="last_name">
        <input type="text" name="email">
        <input type="text" name="password">
        <input type="text" name="confirm_password">
        <input type="submit" name="submit">
    </form>
</div>
<!--/ .wrap-->

<!-- - - - - - - - - - - - - end Slider - - - - - - - - - - - - - - -->
