<?php
$this->headTitle()->prepend('Confirm');
require 'module/Users/view/users/utils/user_label.php';
?>

<div class="wrap">

	<script src="/js/confirm.js" type="text/javascript"></script>





	<div id="tabs">
		<ul>
			<li><a href="#tabs-2"><?php echo $user_labels[orgManagement]?></a></li>
			<li><a href="#tabs-1"><?php echo $user_labels[personalInfo]?></a></li>
			<li><a href="#tabs-3"><?php echo $user_labels[taskManagement]?></a></li>
		</ul>
		<div id="tabs-1" style="height: 800px">
		<?php echo $this->partial('users/login/personalInfo', array(
		    'user' => $user,
		    'userInfo' => $userInfo,
		    'org' => $org))?>	
		</div>
	
	   <div id="tabs-2">
	   <?php echo $this->partial('users/login/manageOrg', array(
	       'user' => $user, 
	       'org' => $org))?>
	   </div>
	   <div id="tabs-3">
	   add the tasks managements here.
	   </div>
</div>
</div>
<!-- /.wrap -->

<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script
	src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script
	src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>

<!-- The basic File Upload plugin -->
<script src="/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/js/jquery.fileupload-image.js"></script>

<!-- The file Upload image  -->
<script src="/js/upload-image.js"></script>
