<?php 
    $this->headTitle()->prepend('Login'); 
    
?>
<script src="/js/login.js" type="text/javascript"></script>
<!-- - - - - - - - - - - - - - - Main - - - - - - - - - - - - - - - - -->
	<div class="banner">
		<h1> 一个帐户，畅享 ttruus 所有服务！ </h1>
		<h2 class="hidden-small"> 使用您的 ttruus 帐户登录 </h2>
		<div id="error">
	   <?php if ($this->error): ?>
            <p class="error">登陆出错，请参考如下错误信息！</p>
			<p><?php echo $this->errorMessage;?></p>			
       <?php endif ?>
	</div>
		
	</div>
		
	<div class="card signin-card clearfix">
		<img class="profile-img" alt="" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png">
		<p class="profile-name"></p>
		<?php 
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, array('controller'=>'Login', 'action' => 'process')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('id', 'loginform');

        echo $this->form()->openTag($form);
        ?>		
			<?php 
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
			<br>
			<?php 
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
            <?php if ($this->error): ?>
                <p class="error">
                    用户名与密码不符，请重新输入！
                </p>
            <?php endif ?>
            <?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>								
			<label class="remember">
				<input id="PersistentCookie" type="checkbox" checked="checked" value="yes" name="PersistentCookie">
				<span> 保持登录状态 </span>
			</label>
			<input type="hidden" value="1" name="rmShown">
			<a id="link-forgot-passwd" class="need-help-reverse" href="https://accounts.google.com/RecoverAccount?continue=http%3A%2F%2Fwww.google.com.hk%2F"> 需要帮助？ </a>
		  <?php echo $this->form()->closeTag() ?>
	</div>
	<p class="create-account">
  		<a id="link-signup" href="/users/register" id="link-signup">
  		创建帐户
  		</a>
  	</p>
	<!-- - - - - - - - - - - - - - - End Main - - - - - - - - - - - - - - -->		
	

