<?php 
    $this->headTitle()->prepend('Login'); 
    require 'module/Users/view/users/utils/user_label.php';
    
?>
<script src="/js/login.js" type="text/javascript"></script>
<!-- - - - - - - - - - - - - - - Main - - - - - - - - - - - - - - - - -->
	<div class="banner">
		<h1> <?php echo $user_labels[title1]?> </h1>
		<h2 class="hidden-small"><?php echo $user_labels[title2]?> </h2>
		<div id="error">
	   <?php if ($this->error): ?>
            <p class="error"><?php echo $user_labels[loginError]?></p>
			<p><?php echo $this->errorMessage;?></p>			
       <?php endif ?>
	</div>
		
	</div>
		
	<div class="card signin-card clearfix">
		<img class="profile-img" alt="" src="/images/avatar_2x.png">
		<p class="profile-name"></p>
		<?php 
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, array('controller'=>'Login', 'action' => 'process')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('id', 'loginform');

        echo $this->form()->openTag($form);
        ?>		
			<?php 
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
			<br>
			<?php 
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
            <?php if ($this->error): ?>
                <p class="error">
                   <?php echo $user_labels[invalidatePassword]?>
                </p>
            <?php endif ?>
            <?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
            <script type="text/javascript">
            $('#submit-button').attr('value', '<?php echo $user_labels[login];?>');
            </script>								
			<label class="remember">
				<input id="PersistentCookie" type="checkbox" checked="checked" value="yes" name="PersistentCookie">
				<span> <?php echo $user_labels[keepLogin]?> </span>
			</label>
			<input type="hidden" value="1" name="rmShown">
			<a id="link-forgot-passwd" class="need-help-reverse" href="https://accounts.google.com/RecoverAccount?continue=http%3A%2F%2Fwww.google.com.hk%2F"> <?php echo $user_labels[needHelp]?>？ </a>
		  <?php echo $this->form()->closeTag() ?>
	</div>
	<p class="create-account">
  		<a id="link-signup" href="/users/register" id="link-signup">
  		<?php echo $user_labels[createAccount]?>
  		</a>
  	</p>
	<!-- - - - - - - - - - - - - - - End Main - - - - - - - - - - - - - - -->		
	

