<?php 
    $this->headTitle()->prepend('Login'); 
    require 'module/Users/view/users/utils/user_label.php';
    
?>
<!-- - - - - - - - - - - - - - - Main - - - - - - - - - - - - - - - - -->
<!-- prepare varible for js -->
<input type="hidden" id="jsNoSuchEmail" value="<?php echo $user_labels[jsNoSuchEmail]?>">
	<div class="banner">
		<h1> <?php echo $user_labels[title1]?> </h1>
		<h2 class="hidden-small"><?php echo $user_labels[title2]?> </h2>
		<div id="error" hidden="hidden">
            <p class="error"><?php echo $user_labels[loginError]?></p>
	</div>
		
	</div>
		
	<div class="card signin-card clearfix">
		<img class="profile-img" alt="" src="/images/avatar_2x.png">
		<p class="profile-name"></p>
		<?php 
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, array('controller'=>'Login', 'action' => 'process')));
        $form->setAttribute('method', 'post');
        $form->setAttribute('id', 'loginform');

        echo $this->form()->openTag($form);
        ?>		
			<?php 
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?>
			<br>
			<?php 
            echo $this->formElement($form->get('password'));
            echo $this->formElementErrors($form->get('password'));
            ?>
                <div class="error" id="noMatch" hidden="hidden">
                    <p>
                       <?php echo $user_labels[invalidatePassword]?>
                       <br>
                    <?php echo $user_labels['no']?><span id="errorTimes"></span><?php echo $user_labels['loginErrorTimes']?>
                    </p>
                </div>
            <?php 
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>
            <script type="text/javascript">
            $('#submit-button').attr('value', '<?php echo $user_labels[login];?>');
            </script>								
			<label class="remember">
				<input id="PersistentCookie" type="checkbox" checked="checked" value="yes" name="PersistentCookie">
				<span> <?php echo $user_labels[keepLogin]?> </span>
			</label>
			<a id="link-forgot-passwd" class="need-help-reverse" href="/users/resetPassword/index"> <?php echo $user_labels[forgetPassword]?>？ </a>
		  <?php echo $this->form()->closeTag() ?>
		  <div id="loadingImg" hidden="hidden" class="mycenter" style="width: 20px;" >
		      <img alt="loading" src="/images/loading.gif">
		  </div>
	</div>
	<p class="create-account">
  		<a id="link-signup" href="/users/register" id="link-signup">
  		<?php echo $user_labels[createAccount]?>
  		</a>
  	</p>
	<!-- - - - - - - - - - - - - - - End Main - - - - - - - - - - - - - - -->		
<script src="/js/login.js" type="text/javascript"></script>	

