
<?php require 'module/Users/view/users/utils/user_label.php';?>
<!-- prepare information -->
<input type="hidden" id="user_email_value"
	value="<?php echo $user->email; ?>">

<div id="change_password" class="wrap">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1"><?php echo $user_labels[changePassword]?></a></li>
		</ul>
		<div id="tabs-1">
		<br>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('users/setting', array(
    'controller' => 'Setting',
    'action' => 'processPassword'
)));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'changePassword');
echo $this->form()->openTag($form);
?>
               <div id="changePassword">
                <div class="error mycenter" id="passwordError" hidden="hidden" style="width: 200px;"><?php echo $user_labels[changePasswordError]?></div>
                <br>
                <table class="mycenter">
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('old_password')); ?></th>
    			         <td >
    			             <?php 
                                echo $this->formElement($form->get('old_password'));
                                echo $this->formElementErrors($form->get('old_password'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('password')); ?></th>
    			         <td>
    			             <?php 
                                echo $this->formElement($form->get('password'));
                                echo $this->formElementErrors($form->get('password'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('confirm_password')); ?></th>
    			         <td>
    			             <?php 
                                echo $this->formElement($form->get('confirm_password'));
                                echo $this->formElementErrors($form->get('confirm_password'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <td>
    			         <?php
                            echo $this->formElement($form->get('submit'));
                            echo $this->formElementErrors($form->get('submit'));
                        ?>
    			         </td>
    			     </tr>
    			</table>
    			         <?php echo $this->form()->closeTag()?>
    	   
    		<div style="width:20px;" class="mycenter">
                <img hidden="hidden"  id="loadingImg"  alt="" src="/images/loading.gif">
    		</div>
    	</div>
    		<div class="mycenter" hidden="hidden" id="changeSuccess" style="width: 610px">
                <br>
                <br>
                <h3 ><?php echo $user_labels[confirm_closeWindow] ?></h3>
                <br>
                <br>
            </div>
		</div>
	</div>
</div>
<!-- The Password setting validation plugin -->
<script src="/js/change-password.js" type="text/javascript"></script>
