<?php
$this->headTitle()->prepend('setting');
//include_once 'module/Users/view/layout/top_panel.php';
?>
<!-- prepare information -->
<input type="hidden" id="user_email_value" value="<?php echo $user->email; ?>">

<div class="wrap">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">个人资料</a></li>

		</ul>
		<div id="tabs-1">
			<div id="tabs-1">
			<div id="showPhoto">
                <?php 
                echo $this->partial('layout/showTnPhoto.phtml', array(
                    'user_firstname' => $user->firstname,
                    'user_id' => $user->id
                ));
                //include_once 'module/Users/view/layout/showTnPhoto.php';?>
                <br>
                <br>
				<div>
                    <?php if ($this->error): ?>
                    <p class="error">There were one or more isues with
						your submission. Please correct them as indicated below.</p>
                    <?php endif ?>
                    
                    <?php
                    $form = $this->form;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('users/media', array(
                        'controller' => 'Media',
                        'action' => 'processUpload'
                    )));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('id', 'fileupload');
                    
                    echo $this->form()->openTag($form);
                    ?>
                    
                    <span class="btn btn-success fileinput-button" style="margin-left: 16px;"><i
						class="glyphicon glyphicon-plus" ></i><span>更新头像</span>
                    		      <?php
                            echo $this->formElement($form->get('imageupload'));
                            echo $this->formElementErrors($form->get('imageupload'));
                            ?>
                    </span> <br> <br>
					<p>
                     <?php
                    //echo $this->formElement($form->get('submit'));
                    //echo $this->formElementErrors($form->get('submit'));
                    ?>
                    </p>
                    <?php echo $this->form()->closeTag()?>
                </div>
            </div>
                
                 <!-- userSetForm -->
                 <br>
			     <br>
                <div id="showInfo">
                <?php if ($this->error): ?>
                    <p class="error">There were one or more isues with
						your submission. Please correct them as indicated below.</p>
                <?php endif ?>
                
                <?php
                    $form = $this->userSetForm;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('users/setting', array(
                        'controller' => 'Setting',
                        'action' => 'process'
                    )));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('id', 'userSet');
                    
                    echo $this->form()->openTag($form);
                    ?>
                <h5>基本信息</h5>
                <script type="text/javascript">
                $(function(){
                	$("#first_name").attr("value", $("#first_name_value").val());
                	$("#last_name").attr("value", $("#last_name_value").val());
                	$("#title").attr("value", $("#title_value").val());
                	$("#telephone1").attr("value", $("#telephone1_value").val());
                	$("#telephone2").attr("value", $("#telephone2_value").val());
                	//$("#address").attr("value", $("#address_value").val());
                	document.getElementById('address').value=$("#address_value").val();
                	//male 1, female 2
                	if($("#sex_value").val()=='1'){
                	    $("#male").attr("checked", "checked");
                	}else if($("#sex_value").val()=='2'){
                		$("#female").attr("checked", "checked");
                	}
                });
                </script>
                <input type="hidden" id="user_id_value" name="id" value="<?php echo $user->id;?>" >
                <table>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('first_name')); ?></th>
    			         <td >
    			             <input type="hidden" id="first_name_value" value="<?php echo $user->first_name;?>">
    			             <?php 
                                echo $this->formElement($form->get('first_name'));
                                echo $this->formElementErrors($form->get('first_name'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('last_name')); ?></th>
    			         <td>
    			         <input type="hidden" id="last_name_value" value="<?php echo $user->last_name;?>">
    			             <?php 
                                echo $this->formElement($form->get('last_name'));
                                echo $this->formElementErrors($form->get('last_name'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('sex')); ?></th>
    			         <td>
    			             &nbsp&nbsp
        			         <input type="hidden" id="sex_value" value="<?php echo $user->sex;?>">
        			         <input type="radio" id="male" name="sex" value="1">&nbsp男&nbsp&nbsp
        			         <input type="radio" id="female" name="sex" value="2">&nbsp女
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('title')); ?></th>
    			         <td>
    			         <input type="hidden" id="title_value" value="<?php echo $user->title;?>">
    			             <?php 
                                echo $this->formElement($form->get('title'));
                                echo $this->formElementErrors($form->get('title'));
                             ?>
    			         </td>
    			     </tr>
    			</table>
                <hr>
                <h5>通讯信息</h5>    
                <table>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('telephone1')); ?></th>
    			         <td>
    			         <input type="hidden" id="telephone1_value" value="<?php echo $user->telephone1;?>">
    			             <?php 
                                echo $this->formElement($form->get('telephone1'));
                                echo $this->formElementErrors($form->get('telephone1'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('telephone2')); ?></th>
    			         <td>
    			         <input type="hidden" id="telephone2_value" value="<?php echo $user->telephone2;?>">
    			             <?php 
                                echo $this->formElement($form->get('telephone2'));
                                echo $this->formElementErrors($form->get('telephone2'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('address')); ?></th>
    			         <td>
    			         <input type="hidden" id="address_value" value="<?php echo $user->address;?>">
    			             <?php 
                                echo $this->formElement($form->get('address'));
                                echo $this->formElementErrors($form->get('address'));
                             ?>
    			             
<!--     			         <textarea id="address" rows="8" cols="80"></textarea> -->
    			         </td>
    			     </tr>
    		      </table>
    		      <br>
    			         <?php
                            echo $this->formElement($form->get('submit'));
                            echo $this->formElementErrors($form->get('submit'));
                        ?>
                <?php echo $this->form()->closeTag()?>
                </div>
			</div>
		</div>
	</div>
</div>

<!-- /.wrap -->


<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Load-Image/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="http://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>

<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/js/jquery.fileupload-image.js"></script>
<!-- The File Upload validation plugin -->
<script src="/js/jquery.fileupload-validate.js"></script>

<script src="/js/setting.js" type="text/javascript"></script>
