<?php
$this->headTitle()->prepend('setting');
require 'module/Users/view/users/utils/user_label.php';
?>
<!-- prepare information -->

<div class="wrap">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1"><?php echo $user_labels[personalInfo]?></a></li>

		</ul>
		<div id="tabs-1" style="height: 800px">
		  <div class="tab-left">
		      <?php echo $this->partial('users/setting/tab-left.phtml');?>
		  </div>
		  <div class="tab-right">
		      <?php echo $this->partial('users/setting/tab-right.phtml');?>
		  </div>
		  
		</div>
	</div>
</div>

<!-- /.wrap -->


<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/js/jquery.fileupload-process.js"></script>
<!-- The File Upload validation plugin -->
<script src="/js/jquery.fileupload-validate.js"></script>

<script src="/js/setting.js" type="text/javascript"></script>
