<?php
$this->headTitle()->prepend('setting');
require 'module/Users/view/users/utils/user_label.php';
?>
<!-- prepare information -->
<input type="hidden" id="user_email_value" value="<?php echo $user->email; ?>">

<div class="wrap">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1"><?php echo $user_labels[personalInfo]?></a></li>

		</ul>
		<div id="tabs-1" style="height: 800px">
		  <div class="tab-left">
			<div id="showPhoto">
                <?php 
                echo $this->partial('layout/showTnPhoto.phtml', array(
                    'user_firstname' => $user->firstname,
                    'user_id' => $user->id
                ));
                ?>
                <br>
				<div>
                    <?php if ($this->error): ?>
                    <p class="error"><?php echo $user_labels[error]?></p>
                    <?php endif ?>
                    
                    <?php
                    $form = $this->form;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('users/media', array(
                        'controller' => 'Media',
                        'action' => 'processUpload'
                    )));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('id', 'fileupload');
                    
                    echo $this->form()->openTag($form);
                    ?>
                    
                    <span class="btn btn-success fileinput-button" style="margin-left: 16px;"><i
						class="glyphicon glyphicon-plus" ></i><span><?php echo $user_labels[updatePhoto]?></span>
                    		      <?php
                            echo $this->formElement($form->get('imageupload'));
                            echo $this->formElementErrors($form->get('imageupload'));
                            ?>
                    </span> <br> <br>
					<p>
                     <?php
                    //echo $this->formElement($form->get('submit'));
                    //echo $this->formElementErrors($form->get('submit'));
                    ?>
                    </p>
                    <?php echo $this->form()->closeTag()?>
                </div>
            </div>
            <dl class="shortcut-menue">
                <dt><?php echo $user_labels[shortCutChannel]?></dt>
                <dd>
                    <ul>
                        <li  class="ui-state-default ui-corner-all iconSize" title=".ui-icon-locked">
                            <a target="_blank" href="/users/setting/changePassword"><span class="ui-icon ui-icon-locked"></span></a>
                        </li>
                        <li class="iconText">
                            <a target="_blank" href="/users/setting/changePassword"><?php echo $user_labels[changePassword]?></a>
                        </li>
                    </ul>
                </dd>
            </dl>
          </div>
          <div class="tab-right">   
                 <!-- userSetForm -->
			     <br>
            <div id="showInfo">
                <div class="error mycenter" id="settingError" hidden="hidden" style="width: 200px;"><?php echo $user_labels[systemBusy]?></div>
                
                <?php
                    $form = $this->userSetForm;
                    $form->prepare();
                    $form->setAttribute('action', $this->url('users/setting', array(
                        'controller' => 'Setting',
                        'action' => 'process'
                    )));
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('id', 'userSet');
                    
                    echo $this->form()->openTag($form);
                    ?>
                <h5><?php echo $user_labels[baseInfo]?></h5>
                <script type="text/javascript">
                $(function(){
                	$("#first_name").attr("value", $("#first_name_value").val());
                	$("#last_name").attr("value", $("#last_name_value").val());
                	$("#title").attr("value", $("#title_value").val());
                	$("#telephone1").attr("value", $("#telephone1_value").val());
                	$("#telephone2").attr("value", $("#telephone2_value").val());
                	//$("#address").attr("value", $("#address_value").val());
                	document.getElementById('address').value=$("#address_value").val();
                	//male 1, female 2
                	if($("#sex_value").val()=='1'){
                	    $("#male").attr("checked", "checked");
                	}else if($("#sex_value").val()=='2'){
                		$("#female").attr("checked", "checked");
                	}else if($("#sex_value").val()=='3'){
                		$("#unknown").attr("checked", "checked");
                	}
                });
                </script>
                <table>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('first_name')); ?></th>
    			         <td >
    			             <input type="hidden" id="first_name_value" value="<?php echo $user->first_name;?>">
    			             <?php 
                                echo $this->formElement($form->get('first_name'));
                                echo $this->formElementErrors($form->get('first_name'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('last_name')); ?></th>
    			         <td>
    			         <input type="hidden" id="last_name_value" value="<?php echo $user->last_name;?>">
    			             <?php 
                                echo $this->formElement($form->get('last_name'));
                                echo $this->formElementErrors($form->get('last_name'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('sex')); ?></th>
    			         <td>
    			             &nbsp;&nbsp;
        			         <input type="hidden" id="sex_value" value="<?php echo $userInfo->sex;?>">
        			         <input type="radio" id="male" name="sex" value="1">&nbsp;<?php echo $user_labels[male]?>&nbsp;&nbsp;
        			         <input type="radio" id="female" name="sex" value="2">&nbsp;<?php echo $user_labels[female]?>&nbsp;&nbsp;
        			         <input type="radio" id="unknown" name="sex" value="3">&nbsp;<?php echo $user_labels[unknown]?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('title')); ?></th>
    			         <td>
    			         <input type="hidden" id="title_value" value="<?php echo $userInfo->title;?>">
    			             <?php 
                                echo $this->formElement($form->get('title'));
                                echo $this->formElementErrors($form->get('title'));
                             ?>
    			         </td>
    			     </tr>
    			</table>
                <hr>
                <h5><?php echo $user_labels[contactInfo]?></h5>    
                <table>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('telephone1')); ?></th>
    			         <td>
    			         <input type="hidden" id="telephone1_value" value="<?php echo $userInfo->telephone1;?>">
    			             <?php 
                                echo $this->formElement($form->get('telephone1'));
                                echo $this->formElementErrors($form->get('telephone1'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('telephone2')); ?></th>
    			         <td>
    			         <input type="hidden" id="telephone2_value" value="<?php echo $userInfo->telephone2;?>">
    			             <?php 
                                echo $this->formElement($form->get('telephone2'));
                                echo $this->formElementErrors($form->get('telephone2'));
                             ?>
    			         </td>
    			     </tr>
    			     <tr>
    			         <th class="showInfoTd"><?php echo $this->formLabel($form->get('address')); ?></th>
    			         <td>
    			         <input type="hidden" id="address_value" value="<?php echo $userInfo->address;?>">
    			             <?php 
                                echo $this->formElement($form->get('address'));
                                echo $this->formElementErrors($form->get('address'));
                             ?>
    			             
<!--     			         <textarea id="address" rows="8" cols="80"></textarea> -->
    			         </td>
    			     </tr>
    		      </table>
    		      <br>
    			         <?php
                            echo $this->formElement($form->get('submit'));
                            echo $this->formElementErrors($form->get('submit'));
                        ?>
                <?php echo $this->form()->closeTag()?>
                </div>
        		<div style="width:20px;"  class="mycenter">
                    <img id="loadingImg" hidden="hidden" alt="" src="/images/loading.gif">
        		</div>
		  </div>  
		</div>
	</div>
</div>

<!-- /.wrap -->


<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<script src="/js/jquery.fileupload-process.js"></script>
<!-- The File Upload validation plugin -->
<script src="/js/jquery.fileupload-validate.js"></script>

<script src="/js/setting.js" type="text/javascript"></script>
