<?php echo $this->doctype(); 
require_once 'default_label.php';
?>

<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle($this->translate('ttruus'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <meta name="description" content="信息分享" />
	    <meta name="author" content="ttruus" />
	    
	    <!-- styles -->
	    <?php echo $this->headlink()->prependStylesheet($this->basePath() . '/css/style.css')
	                                ->prependStylesheet($this->basePath() . '/css/start/jquery-ui-1.10.3.custom.css')
	                                ->prependStylesheet($this->basePath() . '/css/1140.css')
	                                ->prependStylesheet($this->basePath() . '/css/myStyle.css')
	                               ?>
	     <!-- scripts -->
	     <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/jquery-1.9.1.js')
                                      //->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.js') 
                                      ?>
         <script src="/js/jquery-ui-1.10.3.custom.js" type="text/javascript"></script>
         
        

        <!--  ttruus ico -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 
            'href' => $this->basePath() . '/images/favicon.ico'))?>

    </head>
    <body class="h-style-1 text-1 ">
    <!-- - - - - - - - - - - - - - Top Panel - - - - - - - - - - - - - - - - -->	

    <div class="top-line clearfix">
	
	   <div class="topcenter">
	       <ul id="topleft">
    	       <li>
    	           <a href="/"> <?php echo $labels[home]?></a>
    	       </li>
    	       <li>
    	           <a href="">| <?php echo $labels[join]?> </a>
    	       </li>
    	       <li>
    	           <a href="">| <?php echo $labels[about]?> </a>
    	       </li>
	       </ul>
		
	       <ul id="topright">
    	       <li>
    	           <a href="/users/register" >| <?php echo $labels[register]?> </a>
    	       </li>
    	       <li>
    	           <a href="/users/login" ><?php echo $labels[login]?> </a>
    	       </li>
    	       
	       </ul>
		</div>
	   	
    </div><!--/ .top-line-->
    <!-- - - - - - - - - - - - - end Top Panel - - - - - - - - - - - - - - - -->	

    	
	
	<!-- - - - - - - - - - - - - - Header - - - - - - - - - - - - - - - - -->	
	<div class="wrap">
	
    	<header id="header" class="clearfix">
    		
    		<a href="index.html" id="logo">
    			<h1><span class="tcolor"><?php echo $labels[logo]?> </span></h1>
    		</a>
    	</header><!--/ #header-->
	</div>
	
	
	<!-- - - - - - - - - - - - - - end Header - - - - - - - - - - - - - - - - -->	
	
		
       <!-- beging the container --> 
      <div class="container">
            <?php echo $this->content; ?>
            
      </div> <!-- /container -->
<?php
echo $this->partial('layout/footer.phtml'); 
?>
    </body>
</html>