<?php require_once 'footer_label.php';?>
<div name="footer">
	<!--footer with copy right  -->
	<div class="wrap">

		<footer id="footer" class="clearfix">
			<div id="myfooter">
				<a href=""><?php echo $labels[help]?> |</a> <a href=""> <?php echo $labels[feedback]?> |</a> <a href=""> <?php echo $labels[privateRight]?></a>
			</div>
			<div class="adjective clearfix">
				<div class="copyright">Copyright &copy; 2013-
<?php
date_default_timezone_set('Asia/Shanghai');
echo date('Y');
?>
. by ttruus Technologies Ltd. All rights reserved</div>
			</div>
			<!--/ .adjective-->
		</footer>
		<!--/ #footer-->
	</div>
	<!-- /wrao -->
</div>

<!-- validation js -->
<script src="/js/jquery.validate.js"></script>
<script src="/js/localization/messages_zh.js"></script>

<script type="text/javascript">
$(function(){
	//validate password(6-22)
	jQuery.validator.addMethod("password", function(value, element) {
		return this.optional(element) || /^[\@A-Za-z0-9\!\#\$\%\^\&\*\.\~]*$/.test(value);
	});
	//validate the text,allow chinese charactor
	jQuery.validator.addMethod("username", function(value, element) {
		return this.optional(element) || /^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9])*$/.test(value);
	});
	//validate address allow space and ","
	jQuery.validator.addMethod("address", function(value, element) {
		return this.optional(element) || /^([\u4E00-\uFA29]|[\uE7C7-\uE7F3]|[a-zA-Z0-9]|[,]|[\s])*$/.test(value);
	});

});
</script>
