<div>
	<!--footer with copy right  -->
	<div class="wrap">

		<footer id="footer" class="clearfix">
			<div id="myfooter">
				<a href="">帮助 |</a> <a href=""> 发送反馈 |</a> <a href=""> 隐私权和使用条款</a>
			</div>
			<div class="adjective clearfix">
				<div class="copyright">Copyright &copy; 2013-
<?php
date_default_timezone_set('Asia/Shanghai');
echo date('Y');
?>
. by ttruus Technologies Ltd. All rights reserved</div>
			</div>
			<!--/ .adjective-->
		</footer>
		<!--/ #footer-->
	</div>
	<!-- /wrao -->
</div>
