<?php require 'layout_label.php';?>
<div id="foot">
	<!--footer with copy right  -->
	<div class="wrap">

		<footer id="footer" class="clearfix">
			<div id="myfooter">
				<a href=""><?php echo $labels[help]?> |</a> <a href=""> <?php echo $labels[feedback]?> |</a> <a href=""> <?php echo $labels[privateRight]?></a>
			</div>
			<div class="adjective clearfix">
				<div class="copyright">Copyright &copy; 2013-
<?php
date_default_timezone_set('Asia/Shanghai');
echo date('Y');
?>
. by ttruus Technologies Ltd. All rights reserved</div>
			</div>
			<!--/ .adjective-->
		</footer>
		<!--/ #footer-->
	</div>
	<!-- /wrao -->
</div>

<!-- validation js -->
<script src="/js/jquery.validate.js"></script>
<script src="/js/localization/messages_zh.js"></script>
<script src="/js/jquery.validate.regex.js"></script>


