<?php 
    echo $this->doctype(); 
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle($this->translate('ttruus'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <meta name="description" content="" />
	    <meta name="author" content="ttruus" />
	    
	    
	    <!-- styles -->
	    <?php echo $this->headlink()->prependStylesheet($this->basePath() . '/css/style.css')
	                                ->prependStylesheet($this->basePath() . '/css/start/jquery-ui-1.10.3.custom.min.css')
	                                ->prependStylesheet($this->basePath() . '/css/1140.css')
	                                ->prependStylesheet($this->basePath() . '/css/jquery.fileupload.css')
	                                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
	                               ?>
	   <!-- scripts -->
	   <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      //->prependFile($this->basePath() . 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js')
                                      ?>
        <script src="/js/jquery-1.9.1.js"></script>
        
        <script src="/js/jquery-ui-1.10.3.custom.js" type="text/javascript"></script>
        
        <!--  ttruus ico -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 
            'href' => $this->basePath() . '/images/favicon.ico'))?>
        
        <!-- customer style by Yuhai -->
        <link href="/css/myStyle.css" rel="stylesheet" type="text/css" />

    </head>
    
    <body class="h-style-1 text-1" hidden="hidden">
        <!-- top_panel of user's pages -->
        <?php echo $this->partial('layout/top.phtml');?>
        <!-- beging the container --> 
        <?php echo $this->content; ?>
        <!-- footer of pages -->    
        <?php echo $this->partial('layout/footer.phtml');?>
    </body>
</html>

