<!-- show TnPhoto -->
<script src="/js/photoDialog.js"></script>
<div id="files" class="files" style="height: 149px;">
	<br> <a href="#" id="dialog-link"> <img alt="请更新您的头像"
		class="ui-state-default ui-corner-all" id="photoImg" title="点击放大"
		src="<?php echo $this->url('users/media', array('action' => 'showImage', 'id' => $this->user_id, 'subaction' => 'thumb'));?>"
		style="height: 130px; width: 130px">
	</a>
</div>

<!-- ui-dialog -->
<div id="dialog" title="<?php echo $this->user_firstname;?>">
	<p>
		<input id="imgUrl" type="hidden" value="<?php echo $this->user_id; ?>">
		<img id="userImg">
	</p>
</div>
