<?php $this->headTitle()->prepend('Register'); ?>

<script src="/js/register.js" type="text/javascript"></script>
<script src="/js/captcha.js" type="text/javascript"></script>

<!-- copy from captcha -->
<?php


// Make the page validate
ini_set('session.use_trans_sid', '0');

// Include the random string file
//require 'captcha/rand.php';
// Create a random string, leaving out 'o' to avoid confusion with '0'
$char = strtoupper(substr(str_shuffle('abcdefghjkmnpqrstuvwxyz'), 0, 4));

// Concatenate the random string onto the random numbers
// The font 'Anorexia' doesn't have a character for '8', so the numbers will only go up to 7
// '0' is left out to avoid confusion with 'O'
$str = rand(1, 7) . rand(1, 7) . $char;

// Begin the session
session_start();

// Set the session contents
$_SESSION['captcha_id'] = $str;

?>

<!-- end the captcha -->

<div class="banner">
	<h1>一个帐户，畅享 ttruus 所有服务！</h1>
	<h2 class="hidden-small">建立您的 ttruus 帐户</h2>
</div>
<section class="register">
<?php if ($this->error): ?>
<p class="error">There were one or more isues with your submission.
		Please correct them as indicated below.</p>
<?php endif ?>

<div class="clearfix">
    <div class="sign-up">
        <div class="signup-box">
        <?php
        $form = $this->form;
        $form->prepare();
        $form->setAttribute('action', $this->url(NULL, array(
            'controller' => 'Register',
            'action' => 'process'
        )));
        $form->setAttribute('method', 'post');
        $form->setAttribute('autocomplete', 'off');
        
        echo $this->form()->openTag($form);
        ?>
        <fieldset>
            <legend>
                <strong>名称</strong>
            </legend>
            
                <?php 
                echo $this->formElement($form->get('first_name'));
                echo $this->formElementErrors($form->get('first_name'));
                ?>
                <br>
                <?php 
                echo $this->formElement($form->get('last_name'));
                echo $this->formElementErrors($form->get('last_name'));
                ?>
           
        </fieldset>
        
        <fieldset>
            <legend>
                <strong><?php echo $this->formLabel($form->get('email')); ?></strong>
            </legend>
             <?php                 
                echo $this->formElement($form->get('email'));
                echo $this->formElementErrors($form->get('email'));
             ?>
                
            
        </fieldset>
        
        <fieldset>
            <legend>
                <strong><?php echo $this->formLabel($form->get('password')); ?></strong>
            </legend>
             <?php                 
                echo $this->formElement($form->get('password'));
                echo $this->formElementErrors($form->get('password'));
             ?>            
        </fieldset>
        
        <fieldset>
            <legend>
                <strong><?php echo $this->formLabel($form->get('confirm_password')); ?></strong>
            </legend>
             <?php                 
                echo $this->formElement($form->get('confirm_password'));
                echo $this->formElementErrors($form->get('confirm_password'));
             ?>   
        </fieldset>
        <table>
            <tr>
                
                <td>
                    <div id="captchaimage"><a href="" 
                        id="refreshimg" title="换一张"><img src="/captcha/images/image.php?<?php echo time(); ?>" 
                        alt="请点击" id="captcha_image"/></a></div> 
                </td>
            </tr>
            <tr>
                <td>
                    <input type="text" maxlength="6" class="form-element" name="captcha" id="captcha" placeholder="验证码"/>
                </td>
            </tr>
            <tr>
	  			
	  			<td class="field">
		  			<div id="termswrap">
			  			<input id="terms" type="checkbox" name="terms" checked="checked"/>
			            <label id="lterms" for="terms"><strong>我已阅读并接受</strong><a href="/protocal.html">《ttruus用户协议》</a></label>
		            </div> <!-- /termswrap -->
	  			</td>
	  		 </tr>
	  	</table>

        <?php
        echo $this->formElement($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?>
        
        		
        <?php echo $this->form()->closeTag()?>
        </div>
    </div>
</div>
</section>
<p></p>
