<?php
$this->headTitle()->prepend('task');
require 'module/Users/view/users/utils/user_label.php';
?>
<!-- prepare information -->

<div class="wrap">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">task</a></li>

		</ul>
		<div id="tabs-1" style="height: 800px">
		  <div class="tab-left">
		      tab-left
		  </div>
		  <div class="tab-right">
		      tab-right
		  </div>
		  
		</div>
	</div>
</div>

<script src="/js/createTask.js" type="text/javascript"></script>