<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                        => __DIR__ . '/Module.php',
    'Users\Controller\IndexController' => __DIR__ . '/src/Users/Controller/IndexController.php',
    'UsersTest\Framework\TestCase'        => __DIR__ . '/tests/Users/Framework/TestCase.php',
    'UsersTest\SampleTest'                => __DIR__ . '/tests/Users/SampleTest.php',
);
