<?php
$user_labels = array(
	//login page
    'title1' => '一个帐户，畅享 ttruus 所有服务！',
	'title2' => ' 使用您的 ttruus 帐户登录',
    'error' => '请参考如下错误信息！',
    'loginError' => '登陆出错，请参考如下错误信息！',
    'jsNoSuchEmail' => '该用户邮箱没有注册',
    'invalidatePassword' => '用户名与密码不符，请重新输入！',
    'keepLogin' => '保持登录状态',
    'forgetPassword' => '忘记密码',
    'no' => '第',
    'loginErrorTimes' => '次登录错误，总共有10次机会',
    //request
    'requestName' => '申请者名称',
    'requestTime' => '申请时间',
    'requestAdditionInfo' => '附加信息',
    'respondAction' => '接受／拒绝',
    'waitingRequest' => '等待回应的申请',
    'unreadRequest' => '个未读的申请',
    'invitePeopelJoin' => '邀请其他人加入',
    'inviterEmail' => '被邀请人邮箱',
    //regiter user
    'createAccount' => '创建帐户',
    'name' => '名称',
    'changeImg' => '换一张',
    'click' => '请点击',
    'captcha' => '验证码',
    'accept' => '我已阅读并接受',
    'terms' => '《ttruus用户协议》',
    'registerError' => '注册失败，请重新注册',
    //set userinfo
    'userInfo' => '用户信息',
    'pleaseUpdate' => '请更新',
    'hitEnlarge' => '点击放大',
    'systemBusy' => '系统忙，请稍后再试',
    'uploadError' => '必须是小于2M的图形文件',
    'addInfo' => '请补充您的信息',
    'orgManagement' => '团队管理',
    'personalInfo' => '个人资料',
    'taskManagement' => '任务管理',
    'baseInfo' => '我的基本信息',
    'firstName' => '名字',
    'firstNamePrompt' => '名字(小于18个字符)',
    'lastName' => '姓氏',
    'lastNamePrompt' => '姓氏(小于18个字符)',
    'sex' => '性别',
    'male' => '男',
    'female' => '女',
    'unknown' => '保密',
    'createTime' => '创建时间',
    'LastModifyTime' => '最后一次修改时间',
    'contactInfo' => '我的通讯信息',
    'email' => '电子邮箱',
    'selfDescript' => '个性签名',
    'telephone' => '电话',
    'telephone1' => '电话 1',
    'telephone1Prompt' => '例如：139010888xx',
    'telephone2' => '电话 2',
    'telephone2Prompt' => '例如：010-656588xx',
    'address' => '地区',
    'addressPrompt' => '例如：北京市 朝阳区 xx大厦 100号, 邮编：1000xx',
    //
    'myWorkInfo' => '我的工作信息',
    'login' => '登录',
    'password' => '密码',
    'passwordPrompt' => '密码(5到22个字符)',
    'confirmPassword' => '确认密码',
    'oldPassword' => '原密码',
    'newPassword' => '新密码',
    'confirmNewPassword' => '确认新密码',
    'position' => '职务',
    'positionPrompt' => '例如：项目经理',
    'update' => '提交更新',
    'updatePhoto' => '更新头像',
    'updateLogo' => '更新logo',
    'pleaseUpdateLogo' => '我们还没有自己的logo',
    'register' => '注册',
    'logo' => 'logo',
    
    //manager team
    'myCreateOrgInfo' => '我创建的团队信息',
    'needCreateOrg' => '您还没有创建自己的团队。',
    'delete_member_sure' => '从团队中删除这个成员吗？',
    'orgName' => '团队名称',
    'orgMembers' => '团队成员',
    'orgNamePrompt' => '自由飞翔的鸟',
    'orgInfo' => '团队简介',
    'createMyTeam' => '创建我的团队',
    'manageTeam' => '管理团队',
    'webSite' => '网页地址',
    'webSitePrompt' => 'www.sample.com',
    'joinOrg' => '加入其他人创建的团队',
    'shortCutChannel' => '快速通道',
    'changePassword' => '修改密码',
    'updateInfo' => '更新信息',
    'refresh' => '刷新',
    'search' => '搜索',
    'searchError' => '抱歉，没有这个团队',
    'submit' => '提交',
    'additionInfo' => '补充信息有利于团队管理者接受你的请求',
    'addition' => '补充信息',
    'additionInfoPrompt' => '例如：我是你在XXX公司的朋友',
    'sucesssWaiting' => '请求已经提交，请等待回复',
    'more' => '更多',
    
    //reset password
    'confirm_closeWindow' => '信息已经成功修改，5秒钟后本网页会跳转到主页',
    'nextStep' => '下一步',
    'resetEmail' => '需要找回密码的邮箱账号',
    'randomPassword' => '请输入邮箱收到的验证码',
    'resetPassword' => '重置密码',
    'confirmAccount' => '确认账号',
    'captchaCode' => '安全验证',
    'emailError' => '您输入的邮箱没有注册',
    'captchaError' => '您输入的验证码有误，请重新输入',
    'captcha_Error' => '验证码有误',
    'passwordError' => '您输入的密码有误，请重新输入',
    'emailSuccess' => '验证码已经发送到注册邮箱',
    'captchaSuccess' => '请输入重置的密码',
    'passwordSuccess' => '重置密码成功，请登录',
    //change password
    'changePasswordError' =>'原密码与用户账号不符',
    
    //create task
    'createTask' => '创建任务',
    'createTaskSuccess' => '任务已经成功的创建',
    'createSubTaskSuccess' => '子任务已经成功的创建',
    'createAgain' => '再创建一个',
    'returnTaskManagement' => '返回任务管理',
    'selectTeam' => '选择团队',
    'taskName' => '任务名称',
    'mainTaskName' => '主任务名称',
    'subTaskName' => '子任务名称',
    'taskNamePrompt' => '举办xxx婚礼',
    'subTaskNamePrompt' => '邀请嘉宾',
    'taskDescript' => '任务描述',
    'taskDescriptPrompt' => '签订婚庆公司，确定最终时间和场地，邀请嘉宾。',
    'subTaskDescriptPrompt' => '请于xxx准时参加xxx婚礼。',
    'beginTime' => '开始时间',
    'endTime' => '结束时间',
    'taskAsign' => '任务分配',
    'asignSigleMember' => '分配给一个帮手',
    'asignMutipleMember' => '分配给多个帮手',
    'selectReceiver' => '选择接受任务成员',
    
    //target management
    'targetManagement' => '目标管理',
    
    //help management
    'helpManagement' => '帮手管理',
    
    //commen
    'errorRepeat' => '系统忙，请重新提交'
);